name: Versionamento e Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  versionar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar nova tag
        id: tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
          DEFAULT_BRANCH: main
          RELEASE_BRANCHES: main

      - name: Criar Release no GitHub
        if: steps.tag.outputs.new_tag != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true